//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADPDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEvent
    {
        public int ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<decimal> AdditionalCost { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public string AdditionalComment { get; set; }
    }
}
